Hotfix/initial commits
moengage/inform-client-python pull request #1
Opened 2022-12-15 10:58 UTC by mohammadtariqueanjum

2022-12-19 10:28 UTC, ParasJain-dev commented on inform_client.py
> +import json
change format of package- moengage/inform/client

2022-12-19 10:28 UTC, ParasJain-dev commented on inform_client.py
> +            default_url = 'https://inform-api-00.moengage.com/' + VERSION.v1
pick from constant

2022-12-19 10:31 UTC, ParasJain-dev commented on sandbox_client.py
> +class SandBoxClient(object):
we can create base client and use it in both sandbox and inform_client file and reuse most of this code.

2022-12-19 10:39 UTC, ParasJain-dev commented on inform_client.py
> +        resp = self.session.post(url, data=json.dumps(request_data))
use request package, timeout is available there?

2022-12-19 10:45 UTC, ParasJain-dev commented on inform_client.py
> +            raise InformApiException(resp)
we need to support other type of error handling too like rate limiting and all

2022-12-26 09:27 UTC, asinghal4165 commented on moengage/inform/client/request/inform_sent_request.py
> +from mongoengine import *
Please avoid using * in imports, import individual components

2022-12-26 09:28 UTC, asinghal4165 commented on moengage/inform/client/api/conf/provider.py
> +        return data['test_base_url']
# you can use this logic as well for reading a file

class TestInformLogController(TestCase):
    current_dir = os.path.dirname(os.path.abspath(__file__))

    @staticmethod
    def read_file(name):
        with open(os.path.join(TestInformLogController.current_dir, 'json_data/inform_log_controller/' + name + '.json')) as f:
            return json.load(f)

2022-12-26 10:39 UTC, sumit-moengage requested changes

2022-12-26 10:39 UTC, sumit-moengage commented on moengage/inform/client/request/inform_sent_request.py
> +from mongoengine import *
1. @asinghal4165 is right, do not use wildcard in import statement.
2. please do not use `mongoengine` library apart from MoEngage Repo.
use commons-dao package
Ref- https://github.com/moengage/campaigns-core/blob/master/campaigns-core-scheduler/moengage/campaigns/core/scheduler/models/bts_campaign_bucket.py

2022-12-26 10:39 UTC, sumit-moengage commented on moengage/inform/client/core/client.py
> +        http = urllib3.PoolManager()
please use client from commons lib of moengage instead of urllib3
Ref- https://github.com/moengage/campaign-reports/blob/master/campaign-reports-commons/moengage/campaign_reports/commons/clients/client.py

2022-12-26 10:39 UTC, sumit-moengage commented on moengage/inform/client/core/inform_client.py
> +from mongoengine.errors import FieldDoesNotExist, ValidationError
this will also change, after removing mongoengine change
Ref- https://github.com/moengage/campaign-reports/blob/master/campaign-reports-commons/moengage/campaign_reports/commons/clients/client.py

2022-12-26 12:34 UTC, mohammadtariqueanjum commented on moengage/inform/client/core/client.py
> +        http = urllib3.PoolManager()
Since this is public we are using public packages instead of moengage specific internal packages and clients.

2022-12-26 12:34 UTC, mohammadtariqueanjum commented on moengage/inform/client/core/inform_client.py
> +from mongoengine.errors import FieldDoesNotExist, ValidationError
same as above

2022-12-29 09:38 UTC, rakesh-13 commented on moengage/inform/client/api/configs/config.json
> +    "live_base_url": "https://inform-api-00.moengage.com/v1"
we have region-wise url:
US - https://sandbox-inform-api-01.moengage.com/v1
         https://sandbox-inform-api-01.moengage.com/v1
         
EU - https://sandbox-inform-api-02.moengage.com/v1
         https://sandbox-inform-api-02.moengage.com/v1

AP - https://sandbox-inform-api-03.moengage.com/v1
         https://sandbox-inform-api-03.moengage.com/v1

2022-12-29 09:41 UTC, rakesh-13 commented on moengage/inform/client/core/client.py
> +        resp = http.request(HTTPMethod.POST, url, body=encoded_body, headers=self.headers, timeout=5, retries=3)
request timeout should be 10 sec.

2022-12-29 09:43 UTC, rakesh-13 commented on moengage/inform/client/core/client.py
> +        resp = http.request(HTTPMethod.POST, url, body=encoded_body, headers=self.headers, timeout=5, retries=3)
In what cases we are retrying ?

2022-12-29 10:46 UTC, yashwanth2 commented
Team, let's change the branch name from hotfix to feature/initial_commits.

2022-12-29 11:18 UTC, nehahmoe requested changes

2022-12-29 11:40 UTC, closed without merging