Sandbox and Live Clients for Inform
moengage/inform-client-python pull request #2
Opened 2022-12-29 11:42 UTC by mohammadtariqueanjum

2023-01-06 04:45 UTC, nehahmoe requested changes

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/api/request/schemas/schema-request.json
> +    "required": ["alert_id", "user_id", "transaction_id", "payloads"]
user_id is not mandatory

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/api/response/inform_response.py
> +            "request_type": self.request_type
request_type I think doesnt exist, please confirm

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/api/response/inform_response.py
> +        if status == 400:
request_type is not present, please recheck.
Dont need to add so many if blocks

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/api/response/inform_response.py
> +            }
how about 5xx http status

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/core/inform_client.py
> +            'authorization': 'Basic {}'.format(credentials.decode()),
please use standard headers with the same case.
why are encoding at line 24 and decoding next line?

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/core/inform_client.py
> +    def send(self, request_body):
method name send_alert

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/core/inform_client.py
> +        Post an inform request to Inform environments
Comments needs to be updated as per user documentation

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/core/inform_client.py
> +            return err
why is try catch needed here?
Also what is the err format that is returned?

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/core/inform_client.py
> +        except LocationValueError:
from where is this Error being raised?

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/api/response/inform_response.py
> +class InformClientResponse(object):
what is the significance of this class?
we are mapping the fields as it is. It can as well return the json response from the send function itself

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/core/inform_client.py
> +                resp = http.request("POST", url, body=encoded_body, headers=self.headers, timeout=10, retries=3)
why are we adding this additional block here, in line number 49, retries can be set there itself.

2023-01-06 04:45 UTC, nehahmoe commented on moengage/inform/client/core/inform_client.py
> +        if resp.status == 200:
please remove this, there is no significance of the response class here, it is returning the same json

2023-01-06 12:22 UTC, mohammadtariqueanjum commented on moengage/inform/client/core/inform_client.py
> +            return err
We are returning a validation error message if request validation fails. Its message is a string response. For instance, 
some of the following are error messages. 

> 'alert_id' is a required property

> 'PUSH' is not one of ['EMAIL', 'SMS']

2023-01-06 13:23 UTC, mohammadtariqueanjum commented on moengage/inform/client/core/inform_client.py
> +            'authorization': 'Basic {}'.format(credentials.decode()),
1. standard headers are inherently supported for any urllib3 request. No manual addition required. We are not adding any manual session mechanism here. 
2. base64encode func takes only bytes as input. We are decoding to str and passing as the auth param.

2023-01-10 08:56 UTC, nehahmoe approved these changes

2023-01-10 09:07 UTC, merged